version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/src/.env
    networks:
      - got-net

  frontend:
    build: ./frontend
    ports:
      - "4200:5000"  
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - got-net

networks:
  got-net:
    driver: bridge
